# github: [nu11secur1ty]
patreon: nu11secur1ty
patreon: ["https://www.patreon.com/posts/33882568", patreon.com]
sourceforge: ["https://sourceforge.net/p/insmod-block/code/ci/master/tree/", sourceforge.net]

